[project]
name = "codo"
version = "1.0.0"
description = "(C)ompute (O)perations in (D)ependency (O)rder"
readme = "README.md"
dependencies = []

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
